#! /bin/bash
ln -s $HOME/.dotfiles/init.vim $HOME/.config/nvim/init.vim
ln -s $HOME/.dotfiles/tmux.conf $HOME/.tmux.conf
ln -s $HOME/.dotfiles/tmux.osx.conf $HOME/.tmux.osx.conf

ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc
ln -s $HOME/.dotfiles/zsh $HOME/.zsh

tic xterm-256color.terminfo

# CONTIDIONALY INSTALL WHEN ON MAC
#tic tmux-256color.terminfo
